.gitattributes, .gitignore, .travis.yml, README.md, doc/Makefile, doc/editor.rst, doc/index.rst, doc/ipythonconsole.rst, doc/make.bat
* Enforce LF properly across all files but bat
* Add the makefiles and other ancillaries necessary to build with sphinx
* Add basic building with Travis
* Fix minor issues with docs and meta-files
=> PR: Add Sphinx and Travis building and fix minor issues

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Improvements to content, formatting and harmonization of the issue and PR templates, and add a checklist to the latter.
Not needed; internal change to github templates.
=> PR: Improve GitHub issue and PR templates and add a checklist

CONTRIBUTING.md, LICENSE, README.md
Added a link to the deployed documentation in the Readme and in the Contributing,md document, and added a year range to the copyright notice in the Readme and license to make it properly valid.
Minor/internal change part of initial setup; issue not required.
=> PR: Add doc website link to readme and contributing, and add year to copyright notice

doc/_static/custom.css
Fixes remaining layout issues mentioned in #21 — sets the sidebar headers to the size of the main content subheads, and fixes the spacing around lists (adding bottom margin) and manual linebreaks (removing excess margin). Thanks to @dalthviz for his help with much of the CSS.
Before:
After:
Fixes #25
=> PR: Fix remaining layout issues with sidebar heading font size and element margin heights 

.travis.yml
Adds a link checker to our CI tests, to catch links that are either bad to begin with or have become stale/broken over time. Also touches every file to ensure they are all checked by both builders.
Fixes #35
=> PR: Add the Sphinx link checker to CI checks, and touch all files to ensure all are checked

.gitattributes
Sets some additional file types explicitly as text and binary to be handled appropriately, and also makes sure linguist is detecting the file types and not ignoring them as the point of the project *is* documentation.
Not needed, minor meta/non user visible change.
=> PR: Add more explicit file type rules to gitattributes and make sure linguist doesn't ignore docs

doc/ipythonconsole.rst
Attempts to more explicitly (if briefly) describe connecting to a remote kernel with Spyder, and links to a IPython cookbook article with more technical details. Also, fixes a minor style issue with the IPython link not following the style guide. 
Issue originally raised in spyder-ide/spyder#7147 ; @jmarrietar let us know what you think.
Fixes #38
=> PR: Describe connecting to a remote kernel via ssh and provide link to IPython docs with details

doc/_static/custom.css, doc/conf.py
- Decrease total width to 1000px
- Decrease line-height to 1.57
- Decrease main font-size to 16.8px
- Decrease header font-size by 20%
- Fix style of links on hover
=> PR: More style changes

doc/_static/custom.css, doc/_templates/layout.html, doc/conf.py
Change footer to follow main website one.
Fixes #56
=> PR: Change footer to match main website

doc/_templates/layout.html
Remove redundant `Docs` link
Fixes #65
=> PR: Delete doc link from navbar

doc/_static/custom.css, doc/_templates/layout.html
This is to make the footer more similar to the one in our main website.
=> PR: Some footer adjustmens

doc/ipythonconsole.rst
Updates the section describing connecting to an externel IPython kernel with Spyder to reflect the newly modular ``spyder-kernels`` package in Spyder >=3.3.0. Please review for correctness.
Fixes #53
=> PR: Update procedure to connect to external kernels for Spyder 3.3

doc/installation.rst
Should fix the main issue behind spyder-ide/spyder#7337 Hopefully clarifies the install procedure when cloning from source under Spyder 3.3+. Let me know if I missed anything or something was inaccurate (particularly the install command using ``conda``--will it require ``-c spyder-ide``? I couldn't actually test it since 3.3 doesn't appear to be on ``conda`` yet.
Fixes #55
=> PR: Update installation docs to reflect need to install correct version of spyder-kernels for 3.3+

doc/installation.rst
Updates the dependency list in the install guide to reflect the addition of PyLS, removal of various introspection/analysis packages as direct dependencies, and tweak the purpose of PyZMQ. Counterpart of spyder-ide/spyder#7822 and spyder-ide/spyder-docs#77.
Fixes #73
=> PR: Modify dependency lists in install guide to reflect PyLS changes

doc/ipythonconsole.rst
Based on feedback originally by @jsh9 and others on Gitter.
* Describes how to find the runtime directory for the kernel the user launched on the host
* Clarifies that only an ssh key *or* a keyfile is required, not both
* Notes more precisely which port number is required, and the most common value (22)
Fixes #78
=> PR: Refine description of connect to remote kernel process

doc/ipythonconsole.rst
Resolves the reporting issue by using the suggesting shell command to find the runtime dir, which greatly simplifies the procedure and description thereof.
@bcolsen looks good to you?
Fixes #82
=> PR: Update Jupyter runtime dir command to simpler and correct version

doc/installation.rst
Updates the development build instructions in the install guide to reflect the addition of PyLS and other revisions to the procedure. Counterpart of spyder-ide/spyder#7822 and spyder-ide/spyder-docs#76.
Fixes #75
=> PR: Update dev build install instructions for PyLS

doc/ipythonconsole.rst
As suggested by @bcolsen in a followup to #84 , I've made the Jupyter runtime dir placeholder more repristentative and consistant, and the example PID number more generic and matching the dialog in the Connect the Kernel procedure.
=> PR: Be clearer and more consistent about runtime dir placeholder name

CONTRIBUTING.md
The build command for windows had a typo. instead of "make.bat html" it was specified as "makefile.bat html". I changed this because the name of bat file in /doc is make.bat and not makefile.bat
Fixes #
Changed makefile.bat to make.bat in CONTRIBUTING.md on 3.x branch
=> PR: Fix build command on Windows

.travis.yml
Update the environment in the Travis CI file.
Do we really want our deploy key in there?
=> PR: Update Travis CI with modern environment

.travis.yml
Added a simple conditional to the `.travis.yml` to build the `master` development docs in the `develop` subdirectory of the existing docs site, so they can be more easily previewed before they replace the legacy `3.x` docs. I'll merge this assuming checks pass so we can ensure it works.
Fixes #113
=> PR: Add development build of master branch to .travis.yml

doc/conf.py, doc/first-steps-with-spyder.rst, doc/index.rst, doc/indexvideos.rst, doc/working-with-spyder.rst
1. Added rst file for first section of tutorial videos with the 3 videos embedded 
2. Added rst file for second section of tutorial videos with one video embedded 
3. Added rst file for index of videos 
4. Added index of videos in general index file
5. Added code for directive that is used to embed videos 
This is how the index should look like:
This is a screenshot of the first section of the videos
Fixes #
=> PR Add rst for videos section 1 and 2, add directive for videos in conf

doc/index.rst, doc/indexpanes.rst
=> PR: Update index for docs and add panes index

doc/index.rst, doc/installation.rst
Fixes #89 
Fixes #102 
Fixes #122 
Fixes #123
=> PR: Update install guide for Spyder 4, remove outdated sections, fix outstanding issues and add Binder

.travis.yml, doc/conf.py
=> PR: Add message indicating that documentation is a WIP

doc/first-steps-with-spyder.rst, doc/help.rst, doc/index.rst, doc/installation.rst, doc/onlinehelp.rst, doc/plots.rst, doc/profiler.rst, doc/pylint.rst, doc/variableexplorer.rst, doc/working-with-spyder.rst
There were some extra spaces (and repeated text) that got added accidentally from conflict resolving and also I removed some spaces after the images as the new theme has more spaces than the old one.
Fixes #
=> PR: Fix spaces in docs files to fit new theme

doc/index.rst
* The current title is too long.
* Also, I think `Join the Spyder community` can be simplified and made a bit more friendly by changing it to `Join our community`.
=> PR: Change main title and another one that sounds a bit repetitive

.travis.yml, CONTRIBUTING.md, doc/_static/custom_styles.css, doc/conf.py, doc/index.rst
=> PR: Add cards directive

doc/_static/custom_styles.css
Only apply icons color to the `Where to go now section`
Fixes #
=> PR: Fix custom_style to only affect icon color on a specific section

doc/_static/custom_styles.css, doc/index.rst
As a followup to #142 , tag the "Where to go now?" with a custom `rst-class`, e.g. `blue-icons-32px`, and use that as the selector rather than the dynamic `id` generated directly from the section title.
=> PR: Refactor FA icon coloring in CSS to be more robust

doc/conf.py
A preview:
Depends on https://github.com/spyder-ide/spyder-docs-sphinx-theme/pull/9
=> PR: Update footer config

doc/_static/custom_styles.css
Fix a tiny typo in the custom CSS that resulted in our custom icons not working...again.
Fixes #152
=> PR: Fix typo in CSS resulting in blue icons not working

doc/_static/custom_styles.css
I didn't understand that those changes needed to be included on the theme repo:
https://github.com/spyder-ide/spyder-docs-sphinx-theme/pull/12
=> PR: Remove unnecessary custom styles

README.md
Makes several changes to update the readme now that Spyder 4 is released and to add a link to the development docs, and also convert it to sentence breaks for cleaner diffs, reviews and merges. To clearly view what was actually changed, just see the second commit.
Fixes #159
=> PR: Update the readme for Spyder 4 and convert it to sentence breaks from hard breaks

doc/_static/custom_styles.css, doc/index.rst
Vertically centers the Font Awesome icons on their respective lines
Fixes #165
=> PR: Fix Font Awesome icons to be centered on their lines

doc/index.rst
Added overview item in sidebar pointing to index
Edit: Fixes #164
=> PR: Include overview item in sidebar pointing to index

doc/working-with-spyder.rst
I added the las two videos on profiling and code analysis to working with spyder docs. (All videos from this section are now public in YouTube).
Fixes #
=> PR: Add videos on profiling and code analysis to "Working with Spyder" section

CONTRIBUTING.md, STYLEGUIDE.md
I've made a number of updates to the contributing and style guides to make them up to date with the Spyder 4 release, with changes to the repo over the past year+, and fix various minor issues. I've also broken the Contributing guide by sentence, added a section summarizing the most important points from the style guide leaving the latter more as a reference, and added a prominent link in both documents to the Sphinx reST primer.
I changed the line breaks with the first commit, so I'd strongly advise disincluding it when reviewing to make seeing what I actually changed much easier.
Fixes #139
=> PR: Update style and contributing guide to reflect Spyder 4 release, recent changes to the repo and be more usable for new contributors

STYLEGUIDE.md, doc/basic-first-aid.rst, doc/conf.py, doc/debugging.rst, doc/editor.rst, doc/fileexplorer.rst, doc/findinfiles.rst, doc/help.rst, doc/historylog.rst, doc/installation.rst, doc/internalconsole.rst, doc/onlinehelp.rst, doc/plots.rst, doc/profiler.rst, doc/projects.rst, doc/pylint.rst, doc/variableexplorer.rst
This PR updates the docs to use the new version of the theme by @dalthviz , including adding the necessary config setting for the sidebar depth so they build, and removing the now-unnecessary manual extra vertical space after images (and updating the style guide accordingly).
=> PR: Update the docs repo to work with the new theme changes

doc/_static/custom_styles.css, doc/index.rst
1. Changed title of docs to Welcome to Spyder Documentation and title in sidebar to Welcome
2. Remove h3 titles from join our community section
Fixes #180
=> PR: UX review fixes

doc/_static/custom_styles.css
=> PR: Change stroke color in quickstart to red in theme

doc/_static/custom_styles.css
This uses the same shade of red suggested by Isabella for links on issue https://github.com/spyder-ide/spyder-docs-sphinx-theme/issues/24
=> PR: Change shade of red in tour for a lighter one

scripts/generateredirects.py
Fix the title of the generated redirect pages so links to e.g. the root of the site and unprefixed pages have a better social media previews.
=> PR: Fix title of redirect to look better on previews

doc/_static/custom_styles.css, doc/installation.rst
Added section to link the installers for windows and Mac in the installation guide
Fixes #198
=> PR: Add installers section to installation guide

doc/faq.rst
Adds a FAQ question describing the macOS Big Sur situation and explaining how to work around it, to be linked to from the website download section (once a PR that implements #204 is implemented).
Fixes #203
=> PR: Add FAQ question on installing Spyder on macOS Big Sur

doc/conf.py
Per the discussion in, spyder-ide/website-spyder#182 and the changes implemented in spyder-ide/lektor-icon#16 , the docs-side counterpart of spyder-ide/spyder-docs-sphinx-theme#39 to harmonize the navbar with the main website.
=> PR: Update the navbar to be consistant with the rest of the website

doc/common-illnesses.rst, doc/faq.rst
Updated the chart of kernel versions for Troubleshooting and FAQ
Fixes #195
=> PR: Add new kernel versions in troubleshooting and FAQ

doc/faq.rst
Adds a new section, "About Spyder", with two new FAQ questions: one clarifying that Spyder is open source and fully free to use, one explaining how to use it without running in to the Anaconda EULA restrictions on large commercial companies.
Fixes #202
=> PR: Add FAQ questions on Spyder being open source and Anaconda situation

.github/workflows/deploy.yml, .github/workflows/test.yml, requirements-conda.txt, requirements-dev.txt
It seems that version conflicts with sphinx-multiversion.
=> PR: Avoid installing Jinja2 3 to build the docs

doc/index.rst, doc/indexworkshops.rst, doc/workshops/financial.rst, doc/workshops/plugin-development.rst, doc/workshops/scientific-computing.rst
=> PR: Add workshop index for workshops

doc/installation.rst
spyder 3 is the old name, the new name of the RPM package is spyder.
=> PR: Update openSUSE link

requirements-conda.txt, requirements-dev.txt
- Netlify is failing with an error about Sphinx-multiversion.
- There are some visual glitches, like this one in our main page:
=> PR: Require Sphinx 3 to fix the build and some visual glitches

doc/_static/css/custom_styles.css, doc/faq.rst
The id of the dropdown is being shown as part of the text of the item:
Fixes #
=> PR: Fix standalone installers and packages dropdown in FAQ showing id as text

.pre-commit-config.yaml, doc/conf.py, doc/workshops/financial-analysis.py, doc/workshops/financial.rst, doc/workshops/scientific-computing.py, doc/workshops/scientific-computing.rst
Presently, both the docs linkcheck and the pre-commit checks are failing on `master`. This PR fixes them. Specifically, it:
I plan to reach out to @Linus-Albertus to go through the many spelling and Python errors on those files to determine which are intentional, and resolve the rest.
After we merge this PR, I'll follow it up with another against `4.x` that addresses some additional, less critical issues/updates/simplifications in both branches pre-commit and linkcheck workflows.
=> PR: Fix pre-commit and linkcheck failures on master due to workshops

doc/_static/css/custom_styles.css, doc/_static/js/custom_scripts.js
Simple fixes for the biggest issues making the tour display poorly on small screens; namely, moves the first popover to display below the Spyder window instead of next to it, and doubles the width of the outline of the active element to make it more visible on small screens.
Before and after screenshots on simulated iPhone 6-11:
Note: The logo change is merely due to building in the 4.x branch, and can be ignored.
Fixes #187
=> PR: Improve tour on mobile by moving popover and thickening outline

doc/panes/historylog.rst
Adds clarifications for the number of lines stored in the history pane, and how to manually clear them.
Fixes #252
=> PR: Clarify line limit and how to clear history log

doc/_templates/layout.html, doc/conf.py
Adds an alert banner to the top of the docs for development (currently just feature branches, but will include `master` assuming we branch `5.x` before Spyder 6 is released) and outdated (Spyder 3, Spyder 4) versions that states this and links to the latest supported stable version.
Requires spyder-ide/spyder-docs-sphinx-theme#44 (which in turn is waiting on spyder-ide/spyder-docs-sphinx-theme#43 ) to be merged and the temp commit dropped before merging, but those both should hopefully be merged very soon.
Fixes #188
=> PR: Add banner for out of date and development versions

doc/workshops/financial.rst, doc/workshops/plugin-development.rst, doc/workshops/scientific-computing.rst
There's a broken (and rather non-canonical) link to SciPy in the financial analysis workshop which was causing linkcheck to fail. This fixes that. Followup of PR #302 and implict blocker to #301
=> PR: Fix broken links to SciPy site and others in workshops

doc/workshops/plugin-development.rst
This PR adapts the plugin development workshop to the latest version of cookiecutter, adding links to an updated version of the plugin repository.
Adapts the plugin development workshop to the latest version of cookiecutter.
This PR is not linked to any previous issue.
The only new commit is the last one, at this point it is easier to squash from github because it was not done locally.
=>  PR: Adapt plugin workshop to the most recent version of cookiecutter 

doc/plugins/lineprofiler.rst, doc/plugins/notebook.rst
Adds a warning admonition in the Spyder 5 docs at the top of the pages of the plugins not yet ported to that version, informing users of the fact.
Fixes #304
=> PR: Add warnings to orphan plugins still not yet ported to Spyder 5

doc/faq.rst, doc/troubleshooting/common-illnesses.rst
=> PR: Update Spyder-Kernels version table in TG and remove outdated one in FAQ

doc/installation.rst
I don't know why the version number was specified, but it should probably be updated with every major release or removed. The latter option seems the simplest.
Fixes #313
=> Remove Spyder version in conda create command

.pre-commit-config.yaml
I changed the way sphinx-lint parses its arguments to a more readable/simple/verbose way. Therefore, to avoid you the pain of understanding my changes, while I have my changes in mind, I opened this nice little PR to update your invocation to the new style without changing which checkers are ran.
In the meantime I learnt that spyder uses sphinx-lint so I added [your doc to sphinx-lint tests](https://github.com/sphinx-contrib/sphinx-lint/blob/2c98ec9b5e92c55d6d3ab2fda75f8c848214f20d/populate-xpass.sh#L10) to ensure we'll never introduce a false positive in your doc ♥
None, sadly.
=> Bump to sphinx-lint v0.5 (new argument parsing)

README.md, doc/faq.rst, doc/installation.rst, doc/panes/pylint.rst, doc/plugins/lineprofiler.rst, doc/troubleshooting/basic-first-aid.rst, doc/troubleshooting/call-for-help.rst, doc/troubleshooting/first-steps.rst, doc/videos/working-with-spyder.rst
This fixes several broken, outdated and non-HTTPS links throughout the docs. Since this is a trivial change but needed to get the CIs to pass, and I'll need to hand-merge this to ``master``, I'm going to go ahead and merge once CIs past so I can take care of that post-haste and not cause problems for other contributors.
Blocks #319
=> PR: Fix broken, outdated and non-HTTPS links throughout docs

.gitattributes, .github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/deploy.yaml, .github/workflows/lint.yaml, .gitignore, .pre-commit-config.yaml, .pylintrc, .rstcheck.cfg, .yamllint.yml, LICENSE.txt, README.md, requirements-conda.txt, requirements-dev.txt
Routine maintenance update:
* Update/elide copyright dates
* Update dependency versions to reflect current versions
* Sync pre-commit and hook versions and config with website and then update to latest
* Update gitignore and gitattributes to latest standard versions used in other Spyder repos
* Bump GitHub Actions versions and update config
=> PR: Update dep versions, pre-commit hooks, git files and GH actions

CONTRIBUTING.md
Updates the contributing guide to include the expanded and improved content from the standard version we now use on QtPy, the website, Docrepr and elsewhere, with much more helpful and comprehensive, step by step advice for new contributors walking them through the full process of getting a dev env set up, building the docs and creating a pull request. Most notably, it includes a detailed section walking them through creating a conda or venv/virtualenv environment, as pointed out by @hyounes4560 in #318 . It also includes new standard sections offering help at every step of the way, including:
* Cloning the repo
* Selecting the right branch
* Committing changes
* Pushing branches 
* Opening a PR.
* Etc.
Furthermore, it links to a number of helpful Git tutorials for beginners at the …
=> PR: Update Contributing Guide to latest version w/env setup and much more

doc/panes/variableexplorer.rst
Adds a warning to remind users to not load `.spydata` data unless they created it themselves, or they verifiably trust its source, since it inherently runs untrusted code.
Fixes #328
=> Add warning about only loading .spydata files from trusted sources

doc/faq.rst, doc/installation.rst, doc/plugins/lineprofiler.rst, doc/plugins/notebook.rst, doc/plugins/terminal.rst, doc/workshops/financial.rst, doc/workshops/plugin-development.rst, doc/workshops/scientific-computing.rst
In response to the detailed user feedback on #334 , this PR:
* Expands and updates the guidance in the installation guide surrounding the standalone installers and Anaconda/Miniconda
* Adds more details about the standalone installers, their limitations and how to work around them,
* Adjusts the recommendations accordingly
* Adds a description of installing via Miniconda rather than Anaconda, and guides users toward it
* Makes other related smaller improvements
Additionally, I've revised and updated the other sections in the install guide to ensure they are complete, up to date, and easy to follow.
[Live preview of updated install guide](https://deploy-preview-335--spyder-docs-preview.netlify.app/current/installation.html)
Fixes #334
=> Revise Install Guide to provide better, more up to date guidance

doc/faq.rst, doc/plugins/lineprofiler.rst, doc/plugins/notebook.rst, doc/plugins/terminal.rst
Update channels for install instructions of spyder plugins
Resolves [GHI343](https://github.com/spyder-ide/spyder-docs/issues/343)
=> Update channel in install commands from spyder-ide to conda-forge

doc/Makefile, doc/installation.rst, doc/troubleshooting/call-for-help.rst
The URL to the Spyder page on OpenTeams was broken, so this fixes it. Additionally, color the linkcheck output on GitHub Actions CI so its easier to read.
=> Fix broken link to Spyder page on OpenTeams & linkcheck color

.github/workflows/check.yaml, doc/conf.py
Silences the new linkcheck failures due to Stack Overflow/Stack Exchange apparently blocking requests from GitHub Actions (likely due to scraping or bot concerns), and schedule the linkcheck job to run weekly to catch issues as they arise rather than just with PRs. Also, make the name clearer and allow running on-demand on workflow dispatch.
Unblocks PR #358
=> Run linkcheck weekly and silences SO/SE failures due to blocking GHA

doc/installation.rst, doc/troubleshooting/first-steps.rst
In translating the install guide with @LucyJimenez , we noticed that the the link to the troubleshooting guide pointed to the old wiki version rather than the current docs one. Therefore, this PR updates it; it initially just removed it, but it still seems valuable.
=> Update troubleshooting link in install guide to internal one

requirements.txt
- 0.15 introduces spurious "Section Navigation" sidebars in pages which have no sections (e.g. the Install guide) and 0.16 breaks Fontawesome icons.
- In addition, 0.14 is the version used on Netlify previews, so we'll be sure that PR previews correspond to the deployed version.
Fixes #
=> Pin pydata-sphinx-theme to 0.14
