spyder-ide/spyder-docs

.travis.yml, doc/Makefile
Fix an issue with Travis commands needing quotes, and should trigger the test build of the project with Travis once enabled.
@ccordoba12 Can you enable building this repo with Travis? I lack the necessary rights it seems. Thanks!
=> PR: Fix building on travis and test build

.travis.yml
Setup doctr to only deploy docs from the current 3.x branch for now. Hopefully, we can decide on a longer-term solution soon. Also, test that deployment still works with branch protection.
=> PR: Only deploy 3.x via doctr for now

doc/overview.rst
Removes an outdated reference to Find in Files being able to search a Mercurial repo, but main purpose is to prompt a redeploy of the docs with ``doctr`` to test stricter branch protection settings and their impact on deploying the docs to github pages.
=> PR: Remove outdated reference to searching Mercurial repos and test branch protection

.travis.yml
Thanks to use of an unclearly-document argument, docs were still deploying on master (and presumably other branches) despite not being on the explicit whitelist which should have prevented that. This PR fixes that.
My apologies for the flurry of small PRs; its just been difficult when there isn't a reliable way to test the internal interactions between github, doctr and the code in a PR alone.
=> PR: Fix docs still deploying on master due to ambiguous command argument

doc/overview.rst
Those images were really, really confusing because they display something that doesn't look at all like Spyder.
Note: This doesn't admit discussion @CAM-Gerlach, sorry.
=> PR: Remove all images in Overview

doc/_static/custom.css, doc/conf.py
I stand corrected again. When using `1.57` for `line-height`, `16px` looks much better than `16.8px`.
=> PR: Decrease text font-size to 16px

doc/ipythonconsole.rst
As suggested by @bcolsen in spyder-ide/spyder#7914 , I've added a mention of the use of the kernel ID in the connect to kernel dialog for the connection field. Also did a bit of minor cleanup/consistency conformance to the line spacing in that lists, to make it easier to follow.
=> PR: Add mention of kernel ID number in description of connect to kernel dialog

doc/ipythonconsole.rst
Last try, I got far too many conflicts when rebasing my 3.x.
in one place the backticks did not render well.
another change (first in order) is just for clarity.
=> PR: Fix backticks, add bullets and minor clarifications to IPython Console doc

AUTHORS.txt
CAM Gerlach is now listed as *former* docs maintainer.
Feel free to add whoever is currently the maintainer.
Fixes #98
=> PR: Change description of CAM Gerlach

doc/_static/custom_styles.css
This is necessary to have more separation between the cards of that section and the header of "Join our community".
=> PR: Add a custom bottom margin to sections with cards

doc/installation.rst
Current headers are way too long, which makes the outline on the right to overflow the page and be very hard to read. So I propose to use shorter headers everywhere to fix that.
=> PR: Decrease length of headers in installation guide

doc/_static/custom_styles.css, doc/conf.py
Things look like this now:
I didn't go for full compatibility with our main website (i.e. same padding around the navbar entries) because that would break responsiveness.
This depends on https://github.com/spyder-ide/spyder-docs-sphinx-theme/pull/11
Fixes #144.
=> PR: Make navbar have a similar look to the one on the main website

doc/installation.rst
Per previous discussion, this adds icons to the Additional Help section of the installation guide. Ideas welcome if you want me to change the colors.
=> PR: Add icons to Additional Help section of installation guide

doc/_static/custom_styles.css, doc/findinfiles.rst, doc/first-steps-with-spyder.rst, doc/indexpanes.rst, doc/indexvideos.rst, doc/plots.rst, doc/profiler.rst, doc/variableexplorer.rst, doc/working-with-spyder.rst
Fixes a few accumulated formatting issues and inconsistencies we've noticed and discussed over the course of the docs project so far that we didn't catch on the first pass. Specifically:
* Two docs that had double h3 headers, 
* A mix of sentence and title case h2 headers
* A missing line break at the end of a section with a photo
* A few h2 headers that didn't have the three line breaks before them
* One "related components" section that was h3, not h2
* A file with a few extra blank lines at the end
* A couple spurious directives in toctrees
I did not, as a rule, eliminate trailing whitespace or compress PNGs (both of which are a consistent issue); I can do that at the end, though in a few instances my editor did the former automatically near lines I have touched.
=> PR: Cleanup a few accumulated formatting issues on rewritten docs

README.md
My rationale for these changes:
* Since we're going to have several versions of our docs (Spyder 3, 4, etc), I think it makes little sense to have a screenshot for a specific version.
* I also think that since this is a development repo, our Readme should be focused on giving instructions to new contributors on how to get started. And the screenshot doesn't really help with that.
* Finally, about removing most of the Spyder badges, I think they are kind of distracting for new contributors too. Also, in my humble opinion, I think they belong in the Spyder repo, not here.
=> PR: Remove Spyder badges from Readme

doc/_static/custom_styles.css, doc/conf.py
This centers our iframes (i.e. the frames that contain our Youtube videos) and fixes their bottom margin to be the same as the one for our images.
=> PR: Fix margins for iframes

.travis.yml
Doctr was previously deploying `master` to the `develop` subdir of the site, but with the multiversion changes, it needs to deploy to the root.
=> PR: Set doctr deploy directory to root per multiversion changes

.travis.yml, ci/install.sh, scripts/tagcurrent.py
Fixes the detection of whether we're on a feature/PR branch or a release branch, and consequently the build filtering, output directory and version naming behavior, to work on CIs in detached HEAD mode. Also, several minor improvements:
* Run doctr deploy regardless of branch (it already has its own builtin filtering)
* Use a more recognizable name and email for the git user commiting the deploy to `gh-pages`
* Improve output logging to make empty branches and match patterns more clear
=> PR: Check CI variables to properly detect branch when HEAD detached

doc/_static/custom_scripts.js, doc/_static/custom_styles.css, doc/faq.rst
Adds id anchors to each dropdown (e.g. FAQ question), allowing them to be linked to directly, along with JS that automatically scrolls to them, adjusts for the navbar and gives them some margin, and opens them. I also added link widgets to each one that behave and are styled similarly to the ones next to section headers, that allow easily copying and pasting the links, and bespoke custom classes to each FAQ question to give each a short, unique and permanently linkable name. This is specifically needed for issue #203 and PR #206 so that the FAQ questions can be linked for the side, but should be very useful in general so we can easily link users asking common questions directly to them, instead of just to the section.
Once executablebooks/sphinx-panels#56 is merged, this can be simplified …
=> PR: Add anchors, direct links and buttons to dropdowns, and open and scroll to them automatically

LICENSE.txt, README.md, doc/conf.py
Co-authored-by: storm-sergey <77465944+storm-sergey@users.noreply.github.com>
Updates the various copyright dates in the README, LICENSE and the `conf.py`, merging in the former two from #219 and #220 respectively (with co-commit credit) and doing so in one appropriately named and described commit, branch and PR. Thanks @storm-sergey for that, we appreciate the reminder.
Also, implements a change in the `conf.py` to automatically update the displayed year in the docs in the future when they are rebuilt (and thus are subject to copyright in that new year), and adds a missing red pipe between the date/author and the license link to match the other entries in the docs footer and the one on our main website.
Closes #219 
Closes #220
=> PR: Update copyright dates to 2021 and automatically update in built docs in the future

Makefile
This makes `5.x` the current branch displayed in our docs.
=> PR: Make 5.x the current branch

doc/_static/js/custom_scripts.js
Automatically uncollapses any FAQ questions (or other dropdowns across the pages that use them) that contain the highlighted search term, so it may be more easily found on the page. Previously, when using the site's search function to find a word present on the FAQ page and clicking on the FAQ page in the results, the highlighted term was not visible if it was inside the collapsed FAQ answers. With this PR, any FAQ questions or answers that contain a highlighted term automatically uncollapse themselves when visiting the page.
Fixes #250
=> PR: Uncollapse dropdowns that contain highlighted words (e.g. from search)

.github/workflows/build.yaml, .github/workflows/check.yaml, .github/workflows/deploy.yaml, .github/workflows/lint.yaml
Currently, the CI builds are now failing because the Python `3.x` target shifted to 3.10 in the latest runners. Unfortunately, we're pinned to Sphinx 3.x due to Sphinx-Multiverison, which doesn't support Python 3.10. Accordingly, I've pinned the runners to use Python 3.9, which should fix the builds and at least give us a few years to figure out what we want to do.
Discovered in and currently blocking #301
=> PR: Pin Python version on CIs to 3.9 to fix build failures with 3.10

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
I noticed, thanks to the note by @JulienPalard in #316 , that the Contributing Guide link in the issue template points to Spyder's version, not the docs-specific one (which was almost certainly a mistake on my part at some point many years ago when I created this repo, copying over our Spyder PR template). [Edit—looks like it was 516bcb10 , resyncing it after I presumably rewrrote the latter].
Here', I've updated it, along with a few other minor changes to the issue and PR template. In the future, we should use the template chooser with a few templates and other options to direct users, and perhaps even with an issue form, but this should fix the immediate issue for now.
=> Update contrib guide link and other minor tweaks to issue/PR templates

STYLEGUIDE.md, doc/panes/debugging.rst, doc/panes/editor.rst, doc/panes/fileexplorer.rst, doc/panes/findinfiles.rst, doc/panes/help.rst, doc/panes/historylog.rst, doc/panes/ipythonconsole.rst, doc/panes/onlinehelp.rst, doc/panes/plots.rst, doc/panes/profiler.rst, doc/panes/projects.rst, doc/panes/pylint.rst, doc/panes/variableexplorer.rst
As originally noticed on #322 , the choice of name in the standard "Related components" heading is not ideal—"Related panes" is more clear and specific, shorter, and avoids confusion with any other use of components within the section titles, e.g. as on #322 . Therefore, we should change it. I've updated the style guide accordingly.
=> PR: Rename Related Components to Related Panes for clarity

doc/plugins/index.rst, doc/plugins/lineprofiler.rst, doc/plugins/notebook.rst
Remove the warning in the documentation for the `spyder-lineprofiler` and `spyder-notebook` plugins that they are incompatible with Spyder 5, because this is no longer the case. Also include them both under "Plugins" in the left sidebar.
This reverts PRs #283 and #305.
Fixes #324
=> Re-instate documentation for lineprofiler and notebook plugins

doc/installation.rst
* Otherwise the update process as currently described does nothing because conda simply prints that Spyder is already installed.
* Using a specific version prevents conda from updating the entire environment, which is what happens when you run `conda update spyder`. Instead, this makes conda only update Spyder to the requested version.
* I understand that this would require us to update this command from time to time, but Anaconda takes now from three to six months to update Spyder, so I don't think that's a big issue.
* I noticed this when updating one of our bot messages to close a recurrent bug that shows up in the Spyder version that comes with Anaconda 2022.05. My idea was to point to our docs instead so that more users learn about them.
=> Add latest Spyder version in Anaconda to update command

doc/installation.rst
Anaconda updated Spyder to 5.4.2 a couple of weeks ago, so now we can recommend users to update to it.
=> Install Guide: Update latest available Anaconda version

.pre-commit-config.yaml, doc/panes/debugging.rst, doc/troubleshooting/submit-a-report.rst, doc/workshops/scientific-computing.rst
Fixes markup errors spotted by:
* https://github.com/sphinx-contrib/sphinx-lint/pull/87 (see [these failures](https://github.com/sphinx-contrib/sphinx-lint/actions/runs/6510345052/job/17683828313?pr=87#step:8:531))
cc @CAM-Gerlach
=> Fix incorrect reST indents in docs

doc/_static/css/custom_styles.css
As originally reported by #350, an invisible `::before` element on headings from the theme is blocking clicks to some links in sections above. I'm not entirely sure why its there in the first place, but for now I'll do a quick fix so it doesn't intercept clicks to fix the problem for now, before fixing it more permanently by rebasing on the latest PyData-Sphinx-Theme,
Fixes #350
=> Add a temporary CSS fix for hN::before blocking link clicks

doc/_static/css/custom_styles.css, doc/installation.rst
As fixed for the Spyder website in spyder-ide/website-spyder#223 , the download link for macOS now 404s (as correctly detected by `sphinx linkcheck` due to the Mac installers being renamed with the 5.5.1 release recently and split into x86-64 (Intel) and ARM64 (M1) versions. The simplest fix for now was to just split the existing macOS download button into two, which is exactly what this PR does.
Merging this will fix the linkcheck failure first seen on PR #358 .
=> Add/update links to separate M1 and Intel macOS installers

CONTRIBUTING.md
This PR updates documentation links and enhances the "Fork and Clone" section for improved clarity and usability.
=> Refine commands & Add/update links in contributing guide

doc/installation.rst
After discussion, we changed the Spyder 5.x installer link for macOS Intel x86-64back to the original `Spyder.dmg`, for backward compatibility with existing Spyder updaters and other links in the wild. This fixes the docs (again) to reflect that.
Followup to PR #359 and counterpart to spyder-ide/spyder-website#227
=> Update macOS Intel install link again back to original

doc/_templates/layout.html, doc/conf.py
Currently, the warning banner for old (and new) versions embeds a link title and URL that hardcode the version number of the latest stable docs. With Sphinx-Multiversion that was fine, since all branches were rebuilt in sync so even the old banners would always be up to date, but with the new theme introduced in #367 , this will no longer be the case and unmaintained branches will be static, and not migrated to the new theme. Therefore, we need to update the old banner to be "evergreen" and point to the `/current/` version rather than a hardcoded version value.
I'll also fix any linkcheck issues that may come up.
Required for #367
=> Update version warning banner to always point to the latest stable docs

.github/workflows/build.yaml
The final production deploy of #367 failed because the deploy logic was off; these checks of the GHA env vars need to explicitly check for `'1'` and not just truthy as `'0'` is also truthy. This _should_ fix it. Also, see if the yet another brabd new linkcheck error re-occurs.
=> Explicitly check value of deploy vars in GHA to ensure correct logic

.pre-commit-config.yaml, doc/_static/css/custom_styles.css, doc/installation.rst, doc/videos/first-steps-with-spyder.rst
Discovered in and blocks PR #377
When Spyder 6 was released earlier today, the existing download links all broke due to the changes to the filenames to make them more consistent, as well as some of the extensions, and the new Spyder website without a separate download section. Therefore, we've fixed these issues as well as adding a new Linux installer button.
Technically this is going in before the Spyder 5 branch gets cut, but as the Spyder 5 links would be broken anyway (we'd have to hardcode them to the latest version) and are of increasingly dubious various for new users now that Spyder 6 is (nominally) stable, and this is blocking other PRs that we want to apply to the Spyder 5 docs as well (i.e. for the translations that we've already done), I'm going and merging this to `master` …
=> Fix download links now broken in Spyder 6 & fix error w/stylelint

CONTRIBUTING.md, noxfile.py, requirements.txt
Followup to #377 
As I started to work through adding the relevant translation commands, I ended up finding a number of additional limitations, corner-case bugs and structural  or needing to make a number of significant improvements, fixes and refactorings to the noxfile along the way. To keep things atomic and moving along and avoid jamming large and non-directly-related changes (e.g. adding the whole po-file structure and building that I have locally) into one big PR, I've split out these into a separate one that can (hopefully) get merged quickly prior to me dropping the translations PR that I'm working on in parallel.
Additionally, these improvements also further improve the noxfile's suitability to be easily re-used for many other Spyder projects, with only relatively small and …
=> Improve and refactor noxfile to prepare for translation commands

doc/locales/es/LC_MESSAGES/panes.po, doc/locales/es/LC_MESSAGES/troubleshooting.po
Sphinx Lint's own CI runs on some "friend projects", including this one, and has started failing:
```
E         + sphinx-lint/tests/fixtures/friends/spyder-docs/doc/locales/es/LC_MESSAGES/troubleshooting.po:301: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
E         + sphinx-lint/tests/fixtures/friends/spyder-docs/doc/locales/es/LC_MESSAGES/troubleshooting.po:301: found an unbalanced inline literal markup. (unbalanced-inline-literals-delimiters)
E         + sphinx-lint/tests/fixtures/friends/spyder-docs/doc/locales/es/LC_MESSAGES/troubleshooting.po:601: default role used (hint: for inline literals, use double backticks) (default-role)
E         + sphinx-lint/tests/fixtures/friends/spyder-docs/doc/locales/es/LC_MESSAGES/troubleshooting.po:301: missing …
```
=> Fix Sphinx Lint for Spanish translations

CONTRIBUTING.md, noxfile.py
The new `setup-remotes` action not only sets up the `origin` and `upstream` remotes in both the recommended `fetch` and `push` configuration by connection method (HTTPS or SSH), but also detects and offers to fix issues with the existing config.
=> Add Nox setup & setup-remotes commands + other improvements

.pre-commit-config.yaml, doc/_static/js/language-switcher.js, doc/_static/languages.json, doc/_templates/language-switcher.html, doc/conf.py, noxfile.py, requirements.txt
Adds a fully functional language switcher to the documentation, based on the PyData Sphinx Theme version switcher, for eventual inclusion upstream.
=> Add language switcher to the docs

doc/_static/js/language-switcher.js
During real-world deployed web testing, we discovered a bug in the language switcher URLs on subpages that was not caught in local filesystem testing: a missing trailing slash in the base URL, leading to the main page being displayed instead of subpages. This PR fixes it.
=> Fix bug in language switcher due to lack of trailing slash in base URL
